# Default config file for easylaunch

[example]
aliases = ["ex"] # [] by default
description = "Example Workspace" # "" by default
working-directory = "$HOME" # $HOME by default
commands = [
    "echo 'Hello World!'",
    "echo launching an app",
    "echo launching another app"
]