# Default config file for easylaunch

# This is the only section needed to be setup in the global section
[workspaces]

# example = [
#     "echo doing something",
#     "echo doing something else",
#     "echo doing something else again",
# ]
